version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamevault
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Montar o código-fonte local no contêiner
      - /app/target  # Necessário para build incremental
    environment:
      JAVA_VERSION: 21
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gamevault
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    command: >
      ./mvnw spring-boot:run
        -Dspring-boot.run.profiles=development
        -Dspring.devtools.restart.enabled=true  # Habilita o Live Reload no DevTools
volumes:
  db_data:
